package medicalconsultation;

public enum States {
    REVISION_NO_STARTED,
    REVISION_STARTED,
    ASSESSMENT_ENTERED,
    PRESCRIPTION_EDITING,
    AI_CALLED,
    AI_ANSWERED,
    GUIDELINES_EXTRACTED,
    MEDICINE_ENTERED,
    DOSE_MODIFIED,
    LINE_REMOVED,
    TREATMENT_ENTERED,
    MEDICAL_PRESCRIPTION_FINISHED,
    SIGNATURE_STAMPED,
    HISTORY_AND_PRESCRIPTION_SENT,
    MEDICAL_PRESCRIPTION_PRINTED
}
